package com.mycompany.main.view;

import com.mycompany.main.controller.DisciplineController;
import com.mycompany.main.controller.StudentController;
import com.mycompany.main.controller.TeacherController;

/**
 *
 * @author guilh
 */
public class FrHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrHome.class.getName());

    /**
     * Creates new form FrHome
     * @param sdtController
     * @param tchController
     * @param discController
     */
    public FrHome(StudentController sdtController, TeacherController tchController, DisciplineController discController) {
        initComponents();
        
        pnlDashboard.initControllers(sdtController, tchController, discController);
        pnlStudents.initController(sdtController);
        pnlTeachers.initController(tchController);
        pnlDisciplines.initControllers(discController, tchController, sdtController);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lateralPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnStudents = new javax.swing.JButton();
        btnTeachers = new javax.swing.JButton();
        btnDisciplines = new javax.swing.JButton();
        centralPanel = new javax.swing.JPanel();
        pnlDashboard = new com.mycompany.main.view.PnlDashboard();
        pnlStudents = new com.mycompany.main.view.PnlStudents();
        pnlTeachers = new com.mycompany.main.view.PnlTeachers();
        pnlDisciplines = new com.mycompany.main.view.PnlDisciplines();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graduation-cap.png"))); // NOI18N
        lblTitle.setText("Sistema de Gerenciamento Escolar");
        lblTitle.setToolTipText("");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lblTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTitle.setIconTextGap(10);
        lblTitle.setInheritsPopupMenu(false);

        lateralPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lateralPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("------ Menu ------");
        lateralPanel.add(jLabel1);

        btnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDashboard.setIconTextGap(5);
        btnDashboard.setMaximumSize(new java.awt.Dimension(100, 30));
        btnDashboard.setMinimumSize(new java.awt.Dimension(100, 30));
        btnDashboard.setPreferredSize(new java.awt.Dimension(125, 30));
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        lateralPanel.add(btnDashboard);

        btnStudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-graduate.png"))); // NOI18N
        btnStudents.setText("Alunos");
        btnStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudents.setIconTextGap(5);
        btnStudents.setMinimumSize(new java.awt.Dimension(100, 30));
        btnStudents.setPreferredSize(new java.awt.Dimension(125, 30));
        btnStudents.addActionListener(this::btnStudentsActionPerformed);
        lateralPanel.add(btnStudents);

        btnTeachers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTeachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/workshop.png"))); // NOI18N
        btnTeachers.setText("Professores");
        btnTeachers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTeachers.setIconTextGap(5);
        btnTeachers.setPreferredSize(new java.awt.Dimension(125, 30));
        btnTeachers.addActionListener(this::btnTeachersActionPerformed);
        lateralPanel.add(btnTeachers);

        btnDisciplines.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDisciplines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-open-cover.png"))); // NOI18N
        btnDisciplines.setText("Disciplinas");
        btnDisciplines.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDisciplines.setIconTextGap(5);
        btnDisciplines.setPreferredSize(new java.awt.Dimension(125, 30));
        btnDisciplines.addActionListener(this::btnDisciplinesActionPerformed);
        lateralPanel.add(btnDisciplines);

        centralPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        centralPanel.setLayout(new java.awt.CardLayout());
        centralPanel.add(pnlDashboard, "cardDashboard");
        centralPanel.add(pnlStudents, "cardStudent");
        centralPanel.add(pnlTeachers, "cardTeacher");
        centralPanel.add(pnlDisciplines, "cardDiscipline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lateralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(centralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lateralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(centralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        pnlStudents.updateTable();
        java.awt.CardLayout cl = (java.awt.CardLayout) centralPanel.getLayout();
        cl.show(centralPanel, "cardStudent");
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        pnlDashboard.refreshDashboard();
        java.awt.CardLayout cl = (java.awt.CardLayout) centralPanel.getLayout();
        cl.show(centralPanel, "cardDashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeachersActionPerformed
        pnlTeachers.updateTable();
        java.awt.CardLayout cl = (java.awt.CardLayout) centralPanel.getLayout();
        cl.show(centralPanel, "cardTeacher");
    }//GEN-LAST:event_btnTeachersActionPerformed

    private void btnDisciplinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinesActionPerformed
        pnlDisciplines.updateTableAndSelectors();
        java.awt.CardLayout cl = (java.awt.CardLayout) centralPanel.getLayout();
        cl.show(centralPanel, "cardDiscipline");
    }//GEN-LAST:event_btnDisciplinesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDisciplines;
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnTeachers;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel lateralPanel;
    private javax.swing.JLabel lblTitle;
    private com.mycompany.main.view.PnlDashboard pnlDashboard;
    private com.mycompany.main.view.PnlDisciplines pnlDisciplines;
    private com.mycompany.main.view.PnlStudents pnlStudents;
    private com.mycompany.main.view.PnlTeachers pnlTeachers;
    // End of variables declaration//GEN-END:variables
}
