/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.main.view;

/**
 *
 * @author guilh
 */
public class FrHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrHome.class.getName());

    /**
     * Creates new form FrHome
     */
    public FrHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lateralPanel = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnTeachers = new javax.swing.JButton();
        btnDisciplines = new javax.swing.JButton();
        btnStudents = new javax.swing.JButton();
        centralPanel = new javax.swing.JPanel();
        pnlDashboard = new com.mycompany.main.view.PnlDashboard();
        pnlStudents = new com.mycompany.main.view.PnlStudents();
        pnlTeachers = new com.mycompany.main.view.PnlTeachers();
        pnlDisciplines = new com.mycompany.main.view.PnlDisciplines();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graduation-cap.png"))); // NOI18N
        lblTitle.setText("Sistema de Gerenciamento Escolar");
        lblTitle.setToolTipText("");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTitle.setIconTextGap(10);
        lblTitle.setInheritsPopupMenu(false);

        lateralPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        lateralPanel.add(btnDashboard);

        btnTeachers.setText("Professores");
        btnTeachers.addActionListener(this::btnTeachersActionPerformed);
        lateralPanel.add(btnTeachers);

        btnDisciplines.setText("Disciplinas");
        btnDisciplines.addActionListener(this::btnDisciplinesActionPerformed);
        lateralPanel.add(btnDisciplines);

        btnStudents.setText("Alunos");
        btnStudents.addActionListener(this::btnStudentsActionPerformed);
        lateralPanel.add(btnStudents);

        centralPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        centralPanel.setLayout(new java.awt.CardLayout());
        centralPanel.add(pnlDashboard, "cardDashboard");

        javax.swing.GroupLayout pnlStudentsLayout = new javax.swing.GroupLayout(pnlStudents);
        pnlStudents.setLayout(pnlStudentsLayout);
        pnlStudentsLayout.setHorizontalGroup(
            pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        pnlStudentsLayout.setVerticalGroup(
            pnlStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        centralPanel.add(pnlStudents, "cardStudent");

        javax.swing.GroupLayout pnlTeachersLayout = new javax.swing.GroupLayout(pnlTeachers);
        pnlTeachers.setLayout(pnlTeachersLayout);
        pnlTeachersLayout.setHorizontalGroup(
            pnlTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        pnlTeachersLayout.setVerticalGroup(
            pnlTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        centralPanel.add(pnlTeachers, "cardTeacher");

        javax.swing.GroupLayout pnlDisciplinesLayout = new javax.swing.GroupLayout(pnlDisciplines);
        pnlDisciplines.setLayout(pnlDisciplinesLayout);
        pnlDisciplinesLayout.setHorizontalGroup(
            pnlDisciplinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        pnlDisciplinesLayout.setVerticalGroup(
            pnlDisciplinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        centralPanel.add(pnlDisciplines, "cardDiscipline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lateralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292)
                        .addComponent(centralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lateralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(centralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) centralPanel.getLayout();
        cl.show(centralPanel, "cardStudent");
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) centralPanel.getLayout();
        cl.show(centralPanel, "cardDashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeachersActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) centralPanel.getLayout();
        cl.show(centralPanel, "cardTeacher");
    }//GEN-LAST:event_btnTeachersActionPerformed

    private void btnDisciplinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinesActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) centralPanel.getLayout();
        cl.show(centralPanel, "cardDiscipline");
    }//GEN-LAST:event_btnDisciplinesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDisciplines;
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnTeachers;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JPanel lateralPanel;
    private javax.swing.JLabel lblTitle;
    private com.mycompany.main.view.PnlDashboard pnlDashboard;
    private com.mycompany.main.view.PnlDisciplines pnlDisciplines;
    private com.mycompany.main.view.PnlStudents pnlStudents;
    private com.mycompany.main.view.PnlTeachers pnlTeachers;
    // End of variables declaration//GEN-END:variables
}
