package com.mycompany.main.view;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import com.mycompany.main.controller.*;

/**
 * Dashboards panel
 * @author guilh
 */
public class PnlDashboard extends javax.swing.JPanel {
    private StudentController studentController;
    private TeacherController teacherController;
    private DisciplineController disciplineController;
    private JLabel lblTotalStudents;
    private JLabel lblTotalTeachers;
    private JLabel lblTotalDisciplines;

    public PnlDashboard() {
        initComponentsCustom();
    }

    public void initControllers(StudentController sdt, TeacherController tch, DisciplineController disc) {
        this.studentController = sdt;
        this.teacherController = tch;
        this.disciplineController = disc;
        refreshDashboard();
    }

    private void initComponentsCustom() {
        this.setLayout(new BorderLayout(0, 25));
        this.setBorder(new EmptyBorder(30, 30, 30, 30));

        JPanel pnlWelcome = new JPanel(new GridLayout(2, 1, 0, 4));
        
        JLabel lblTitle = new JLabel("Olá, bem-vindo ao sistema Coordenador!");
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 24));
        lblTitle.setForeground(new Color(40, 40, 40));

        pnlWelcome.add(lblTitle);
        this.add(pnlWelcome, BorderLayout.NORTH);

        JPanel pnlCards = new JPanel(new GridLayout(1, 3, 20, 0));
        pnlCards.setPreferredSize(new Dimension(0, 120));

        lblTotalStudents = new JLabel("0");
        lblTotalTeachers = new JLabel("0");
        lblTotalDisciplines = new JLabel("0");

        pnlCards.add(createMinimalCard("Alunos Matriculados", lblTotalStudents));
        pnlCards.add(createMinimalCard("Professores Ativos", lblTotalTeachers));
        pnlCards.add(createMinimalCard("Disciplinas Ofertadas", lblTotalDisciplines));

        JPanel pnlCenterContainer = new JPanel(new BorderLayout(0, 0));
        pnlCenterContainer.add(pnlCards, BorderLayout.NORTH);

        JPanel pnlInfo = new JPanel(new BorderLayout());
        pnlInfo.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(230, 230, 230), 1),
            new EmptyBorder(20, 20, 20, 20)
        ));

        this.add(pnlCenterContainer, BorderLayout.CENTER);
    }

    private JPanel createMinimalCard(String title, JLabel lblNumber) {
        JPanel card = new JPanel(new BorderLayout(0, 10));
        card.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(220, 220, 220), 1),
            new EmptyBorder(18, 20, 18, 20)
        ));
        card.setBackground(new Color(252, 252, 252));

        JLabel lblHeader = new JLabel(title);
        lblHeader.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblHeader.setForeground(new Color(110, 110, 110));

        lblNumber.setFont(new Font("Segoe UI", Font.BOLD, 36));
        lblNumber.setForeground(new Color(30, 30, 30));

        card.add(lblHeader, BorderLayout.NORTH);
        card.add(lblNumber, BorderLayout.CENTER);
        return card;
    }

    public void refreshDashboard() {
        if (studentController != null) {
            int countStudents = studentController.getAllStudents().size();
            lblTotalStudents.setText(String.valueOf(countStudents));
        }
        if (teacherController != null) {
            int countTeachers = teacherController.getAllTeachers().size();
            lblTotalTeachers.setText(String.valueOf(countTeachers));
        }
        if (disciplineController != null) {
            int countDisciplines = disciplineController.getAllDisciplines().size();
            lblTotalDisciplines.setText(String.valueOf(countDisciplines));
        }
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Gerencie Alunos, Professores e Disciplinas navegando pelo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("menu lateral!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Bem-vindo ao sistema, coordenador!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
